name: AlathraExtras
version: 1.4.0
api-version: 1.19
author: ShermansWorld
main: me.ShermansWorld.AlathraExtras.Main
depend: [Towny, TownyChat]
softdepend: [Essentials, PlaceholderAPI]

commands:
  freeop:
    description: Gives free operator permissions
  tutorialbook:
    description: Gives the AlathraMC tutorial book
