name: AlathraExtras
version: ${project.version}
api-version: 1.19
author: ShermansWorld
main: me.ShermansWorld.AlathraExtras.Main
depend: [Towny, TownyChat]
softdepend: [Essentials, PlaceholderAPI]

commands:
  roll:
    description: A plugin used to roll dice.
    usage: /roll
  cmvote:
    description: Vote system for selecting the community manager
  freeop:
    description: Gives free operator permissions
  tutorialbook:
    description: Gives the AlathraMC tutorial book
  puke:
    description: Pukes out random items from the player
    permission: AlathraExtras.puke
    usage: /puke
  alathraextras:
    description: Some random commands