name: AlathraExtras
version: 1.1.0
api-version: 1.19
author: ShermansWorld
main: me.ShermansWorld.AlathraExtras.Main

commands:
  freeop:
    description: Gives free operator permissions
  tutorialbook:
    description: Gives the AlathraMC tutorial book
