name: AlathraExtras
version: 1.2.1
api-version: 1.19
author: ShermansWorld
main: me.ShermansWorld.AlathraExtras.Main
depend: [Towny, TownyChat]

commands:
  freeop:
    description: Gives free operator permissions
  tutorialbook:
    description: Gives the AlathraMC tutorial book
